export const questions = [
  'FIRST QUESTION',
  'SECOND QUESTION',
  'THIRD QUESTION',
  'FOURTH QUESTION',
  'FIFTH QUESTION',
];

export const answers = [
  [
    'QUESTION 1 FIRST ANSWER',
    'QUESTION 1 SECOND ANSWER',
    'QUESTION 1 THIRD ANSWER',
    'QUESTION 1 FOURTH ANSWER',
  ],
  [
    'QUESTION 2 FIRST ANSWER',
    'QUESTION 2 SECOND ANSWER',
    'QUESTION 2 THIRD ANSWER',
    'QUESTION 2 FOURTH ANSWER',
  ],
  [
    'QUESTION 3 FIRST ANSWER',
    'QUESTION 3 SECOND ANSWER',
    'QUESTION 3 THIRD ANSWER',
    'QUESTION 3 FOURTH ANSWER',
  ],
  [
    'QUESTION 4 FIRST ANSWER',
    'QUESTION 4 SECOND ANSWER',
    'QUESTION 4 THIRD ANSWER',
    'QUESTION 4 FOURTH ANSWER',
  ],
  [
    'QUESTION 5 FIRST ANSWER',
    'QUESTION 5 SECOND ANSWER',
    'QUESTION 5 THIRD ANSWER',
    'QUESTION 5 FOURTH ANSWER',
  ],
];

export const explanations = [
  'FIRST EXPLANATION',
  'SECOND EXPLANATION',
  'THIRD EXPLANATION',
  'FOURTH EXPLANATION',
  'FIFTH EXPLANATION',
];
